&lt;div class=&quot;one-col&quot;&gt;
	&lt;!--
	&lt;h2 style=&quot;border-bottom: 3px #F0BD00 solid;&quot;&gt;
		График работы&lt;/h2&gt;
	&lt;table class=&quot;graph&quot;&gt;
		&lt;tbody&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;31 декабря&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					—&lt;/td&gt;
				&lt;td&gt;
					до&amp;nbsp;17:00&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;&lt;span style=&quot;color:#e45d6b;&quot;&gt;&lt;strong&gt;1 – 4 января&lt;/strong&gt;&lt;/span&gt;&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					&lt;span style=&quot;color:#e45d6b;&quot;&gt;—&lt;/span&gt;&lt;/td&gt;
				&lt;td&gt;
					&lt;strong&gt;&lt;span style=&quot;color:#e45d6b;&quot;&gt;выходные&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;5 января&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					—&lt;/td&gt;
				&lt;td&gt;
					только лавка на&amp;nbsp;&lt;strong&gt;Мичуринском проспекте&lt;/strong&gt; (в&amp;nbsp;обычном режиме)&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;6 января&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					—&lt;/td&gt;
				&lt;td&gt;
					в&amp;nbsp;обычном режиме, &lt;strong&gt;все&amp;nbsp;лавки&lt;/strong&gt;&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;&lt;strong&gt;&lt;span style=&quot;color:#e45d6b;&quot;&gt;7 января&lt;/span&gt;&lt;/strong&gt;&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					&lt;strong&gt;&lt;span style=&quot;color:#e45d6b;&quot;&gt;—&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
				&lt;td&gt;
					&lt;strong&gt;&lt;span style=&quot;color:#e45d6b;&quot;&gt;выходной&lt;/span&gt;&lt;/strong&gt;&lt;/td&gt;
			&lt;/tr&gt;
			&lt;tr&gt;
				&lt;td style=&quot;text-align:right;&quot;&gt;
					&lt;nobr&gt;с&amp;nbsp;8 января&lt;/nobr&gt;&lt;/td&gt;
				&lt;td&gt;
					—&lt;/td&gt;
				&lt;td&gt;
					в&amp;nbsp;обычном режиме&lt;/td&gt;
			&lt;/tr&gt;
		&lt;/tbody&gt;
	&lt;/table&gt;
	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
--&gt;
	&lt;h2&gt;
		Доставка&lt;/h2&gt;
	&lt;p&gt;
		&lt;strong&gt;По Москве&lt;/strong&gt; (в пределах МКАД) - &lt;strong&gt;300 рублей&lt;/strong&gt;;&lt;/p&gt;
	&lt;p&gt;
		Заказ на&amp;nbsp;&lt;strong&gt;2 000 рублей и&amp;nbsp;больше&lt;/strong&gt;:&lt;/p&gt;
	&lt;ul&gt;
		&lt;li&gt;
			в&amp;nbsp;пределах МКАД - бесплатно;&lt;/li&gt;
		&lt;li&gt;
			за&amp;nbsp;МКАД и&amp;nbsp;в другие города - скидка на&amp;nbsp;доставку - 300 рублей;&lt;/li&gt;
		&lt;li&gt;
			стоимость доставки уточняйте по&amp;nbsp;телефону &lt;strong&gt;&lt;a href=&quot;tel:+7 925 735-10-38&quot;&gt;+7 925 735-10-38&lt;/a&gt;&lt;/strong&gt; или&amp;nbsp;по электронной почте chesom@chesom.ru.&lt;/li&gt;
	&lt;/ul&gt;
	&lt;p&gt;
		* Заказы, оформленные:&lt;/p&gt;
<!--	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
	&lt;ul&gt;
		&lt;li&gt;
			&lt;strong&gt;до 12:00&lt;/strong&gt; - доставляются в&amp;nbsp;этот&amp;nbsp;же день;&lt;/li&gt;
		&lt;li&gt;
			после&amp;nbsp;12:00 - на&amp;nbsp;следующий день.&lt;/li&gt;
	&lt;/ul&gt;-->
&lt;p &gt;
	 &lt;div  class="color-circle yellow-circle circle-in-cart margin-right-20px"&gt;&lt;/div&gt;

	&lt;span&gt;  				    	      
	       При заказе «Сыров и гастрономии для гурманов»  до 12:00 доставка сегодня.  При заказе после 12:00  доставка завтра.
	 &lt;/span&gt;
&lt;/p&gt;


&lt;p &gt;
	 &lt;div  class="color-circle lilac-circle circle-in-cart margin-right-20px"&gt;&lt;/div&gt;

	&lt;span&gt;  				    	      
	       При заказе «Продуктов на каждый день»  до 18:00 доставка завтра.  При заказе после 18:00  доставка послезавтра.
	 &lt;/span&gt;
&lt;/p&gt;

&lt;p &gt;
	 &lt;div  class="color-circle green-circle circle-in-cart margin-right-20px"&gt;&lt;/div&gt;

	&lt;span&gt;  				    	      
	       При заказе «Продуктов растительного происхождения»  до 18:00 доставка завтра.  При заказе после 18:00  доставка послезавтра.
	 &lt;/span&gt;
&lt;/p&gt;

	&lt;p&gt;
		Заказ мы отправляем, только если удалось созвониться с&amp;nbsp;покупателем и&amp;nbsp;подтвердить заказ.&lt;/p&gt;
	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
	&lt;p&gt;
		&lt;strong&gt;Если Вы хотите БЕСКОНТАКТНУЮ ДОСТАВКУ, укажите это, пожалуйста в&amp;nbsp;комментарии к&amp;nbsp;заказу, мы оповестим курьера и&amp;nbsp;доставим Ваш заказ до&amp;nbsp;Вашей двери, а&amp;nbsp;курьер отойдет на&amp;nbsp;3 метра.&lt;/strong&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;strong&gt;Все весовые сыры будут гермитично упакованы в&amp;nbsp;вакуум.&lt;/strong&gt;&lt;/p&gt;
	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
	&lt;p&gt;
		&lt;u&gt;&lt;strong&gt;СРОЧНАЯ ДОСТАВКА ПО МОСКВЕ:&lt;/strong&gt;&lt;/u&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;strong&gt;Осуществляется по&amp;nbsp;Москве в&amp;nbsp;течение 3-х часов с&amp;nbsp;момента оформления заказа.&lt;/strong&gt;&lt;/p&gt;
	&lt;p&gt;
		Стоимость срочной доставки - &lt;strong&gt;600 рублей;&lt;/strong&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;strong&gt;Бесплатная срочная доставка - при&amp;nbsp;заказе от&amp;nbsp;6 000 рублей.&lt;/strong&gt;&lt;/p&gt;
	&lt;p&gt;
		Если Вам нужна срочная доставка, просто укажите это в&amp;nbsp;комментарии к&amp;nbsp;заказу.&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;color: rgb(211, 211, 211);&quot;&gt;—&lt;/span&gt;&lt;/p&gt;
	&lt;p&gt;
		Курьер с&amp;nbsp;заказом может подождать вас в&amp;nbsp;течение &lt;strong&gt;15&amp;nbsp;минут&lt;/strong&gt;.&lt;/p&gt;
	&lt;p&gt;
		Ожидание свыше 15&amp;nbsp;минут &lt;strong&gt;оплачивается вами дополнительно&lt;/strong&gt;.&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;color: rgb(211, 211, 211);&quot;&gt;—&lt;/span&gt;&lt;/p&gt;
	&lt;p&gt;
		Все &lt;a href=&quot;http://chesom.ru/cheese&quot; target=&quot;_blank&quot;&gt;сыры&lt;/a&gt; мы упаковываем в&amp;nbsp;специальную бумагу, в&amp;nbsp;которой их можно хранить в&amp;nbsp;холодильнике. Перевозим сыры в&amp;nbsp;термопакетах.&lt;/p&gt;
	&lt;p&gt;
		Как правило, время доставки заказа по&amp;nbsp;Москве (МКАД) не&amp;nbsp;превышает часа.&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;color: rgb(211, 211, 211);&quot;&gt;—&lt;/span&gt;&lt;/p&gt;
	&lt;p&gt;
		Вы также можете самостоятельно забрать свой заказ в&amp;nbsp;наших &lt;a href=&quot;http://chesom.ru/contact&quot;&gt;магазинах&lt;/a&gt;.&lt;/p&gt;
&lt;/div&gt;
&lt;div class=&quot;one-col&quot;&gt;
	&lt;h2&gt;
		Оформление заказа&lt;/h2&gt;
	&lt;p&gt;
		На нашем сайте вы можете оформить свой заказ в&amp;nbsp;любое время суток.&lt;/p&gt;
	&lt;p&gt;
		Мы примем ваш заказ как можно скорее в&amp;nbsp;интервале рабочего времени &lt;strong&gt;&lt;nobr&gt;с 09:00 до&amp;nbsp;21:00&lt;/nobr&gt;&lt;/strong&gt; и&amp;nbsp;перезвоним вам для&amp;nbsp;подтверждения.&lt;/p&gt;
	&lt;p&gt;
		Если вам нужно, чтобы мы перезвонили в&amp;nbsp;какое-то определённое время, напишите об&amp;nbsp;этом в&amp;nbsp;пожелании к&amp;nbsp;заказу.&lt;/p&gt;
	&lt;p&gt;
		&amp;nbsp;&lt;/p&gt;
	&lt;h2&gt;
		Оплата&lt;/h2&gt;
	&lt;p&gt;
		Вы можете оплатить заказ как &lt;strong&gt;при&amp;nbsp;получении&lt;/strong&gt;, так и&amp;nbsp;&lt;strong&gt;сразу на&amp;nbsp;сайте&lt;/strong&gt; (смотрите ниже).&lt;/p&gt;
	&lt;ul&gt;
		&lt;li&gt;
			Если вы выбираете доставку и&amp;nbsp;оплату&amp;nbsp;&lt;strong&gt;при получении&lt;/strong&gt;, то заказ оплачивается курьеру &lt;strong&gt;наличными&lt;/strong&gt;.&lt;/li&gt;
		&lt;li&gt;
			Если вы хотите забрать заказ из&amp;nbsp;&lt;a href=&quot;http://chesom.ru/contact&quot;&gt;магазина&lt;/a&gt;&amp;nbsp;сами, то&amp;nbsp;можете оплатить его как&amp;nbsp;&lt;strong&gt;наличными&lt;/strong&gt;, так и&amp;nbsp;&lt;strong&gt;банковской картой&lt;/strong&gt;.&lt;/li&gt;
	&lt;/ul&gt;
	&lt;p&gt;
		Сразу оплатить заказ на&amp;nbsp;сайте вы можете:&lt;/p&gt;
	&lt;ul&gt;
		&lt;li&gt;
			банковской картой&lt;br /&gt;
			(VISA, MasterCard, МИР);&lt;/li&gt;
		&lt;li&gt;
			электронными деньгами&lt;br /&gt;
			(Яндекс.Деньги, WebMoney, QIWI, и&amp;nbsp;др.);&lt;/li&gt;
		&lt;li&gt;
			наличными&lt;br /&gt;
			(Сбербанк, Евросеть, Связной, Почта России);&lt;/li&gt;
		&lt;li&gt;
			банковским сервисом&lt;br /&gt;
			(Сбербанк ОнЛ@йн, Альфа-Клик и&amp;nbsp;др.);&lt;/li&gt;
		&lt;li&gt;
			SMS-платежом&lt;br /&gt;
			(деньги списываются с&amp;nbsp;баланса телефона).&lt;/li&gt;
	&lt;/ul&gt;
	&lt;p&gt;
		&lt;img alt=&quot;&quot; src=&quot;http://chesom.ru/image/data/files/visa-mastercard.png&quot; style=&quot;width: 165px; height: 19px;&quot; /&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;a href=&quot;http://chesom.ru/oferta&quot;&gt;Договор публичной оферты&lt;/a&gt;&lt;br /&gt;
		&lt;a href=&quot;http://chesom.ru/oferta#rek&quot;&gt;Реквизиты&lt;/a&gt;&lt;br /&gt;
		&lt;a href=&quot;http://chesom.ru/return&quot;&gt;Условия возврата&lt;/a&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;span style=&quot;color: rgb(211, 211, 211);&quot;&gt;—&lt;/span&gt;&lt;/p&gt;
	&lt;p&gt;
		&lt;img alt=&quot;PayAnyWay&quot; src=&quot;http://chesom.ru/catalog/view/theme/chesom/img/payanyway.gif&quot; style=&quot;width: 88px; height: 31px;&quot; /&gt;&lt;/p&gt;
	&lt;p&gt;
		Прием платежей организован через&amp;nbsp;платёжный агрегатор&amp;nbsp;&lt;a href=&quot;https://payanyway.ru&quot;&gt;PayAnyWay&lt;/a&gt;.&lt;/p&gt;
	&lt;p&gt;
		PayAnyWay не&amp;nbsp;передает данные Вашей карты нашему магазину или&amp;nbsp;другим третьим лицам.&lt;/p&gt;
	&lt;p&gt;
		Безопасность платежей банковской картой обеспечивается технологиями защищенного соединения HTTPS (смотрите значок в&amp;nbsp;строке адреса), а&amp;nbsp;также двухфакторной аутентификации пользователя 3D Secure.&lt;/p&gt;
	&lt;p&gt;
		Как правило, для&amp;nbsp;совершения оплаты банки отправляют на&amp;nbsp;ваш номер SMS-сообщение с&amp;nbsp;кодом подтверждения оплаты.&lt;/p&gt;
&lt;/div&gt;
&lt;div class=&quot;one-col&quot;&gt;
	&lt;h2&gt;
		Резка сыра&lt;/h2&gt;
	&lt;p&gt;
		К&amp;nbsp;сожалению, практически невозможно отрезать ровно &lt;strong&gt;100&lt;/strong&gt; или&amp;nbsp;&lt;strong&gt;200&amp;nbsp;грамм&lt;/strong&gt;&amp;nbsp;сыра, поэтому отклонение в&amp;nbsp;весе отрезанного куска может составлять &lt;strong&gt;±30&amp;nbsp;грамм&lt;/strong&gt;.&lt;/p&gt;
	&lt;p&gt;
		Соответственно, итоговая стоимость отрезанного куска сыра может быть чуть больше или&amp;nbsp;чуть меньше (в&amp;nbsp;зависимости от&amp;nbsp;того, сколько именно получится отрезать сыра).&lt;/p&gt;
	&lt;p&gt;
		Мы обязательно уточним у&amp;nbsp;вас, готовы&amp;nbsp;ли вы получить заказ с&amp;nbsp;итоговой стоимостью.&lt;/p&gt;
&lt;/div&gt;
&lt;p&gt;
	&amp;nbsp;&lt;/p&gt;
